# Generated by Django 2.1.4 on 2019-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190516_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='Ipaddress',
            field=models.TextField(),
        ),
    ]
